version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always

  spring:
    image: mdy3722/bubblog-springboot:latest
    container_name: bubblog
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env
