spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bubblog
    username: postgres #${DB_USER}
    password: 1234 #${DB_PASS}
    driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 8080
