spring:
  profiles:
    active: prod  # 기본값 (개발용), 배포 시 prod로 override

server:
  port: 8080
  address: 0.0.0.0


# 스웨거 설정
springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html

logging:
  level:
    root: INFO           # 애플리케이션 전체는 INFO로
    org.springframework: WARN  # 스프링 내부 디버그 로그는 최소화
    org.hibernate.SQL: DEBUG  # SQL 쿼리만 보고 싶으면 DEBUG 유지
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 바인딩 값 보고 싶으면

