spring:

  config:
    import:
      - optional:file:env/dev.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/bubblog
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: disabled
      password: disabled

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${REGION}
    s3:
      bucket: ${BUCKET_NAME}
      presigned-expiration: ${S3_PRESIGNED_EXPIRATION}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

ai:
  server:
    host: ${AI_SERVER_HOST}
    port: ${AI_SERVER_PORT}
